### ISSUE TITLE
建议写一下各个模块的版本

### ISSUE THREAD

**Issue by ww451575464** [yinchangchang/ocr_densenet#11]
这边运行的时候出现很多问题，pytorch的版本需要下调，matplotlibpip2直接安装报错，需要指定2点几的版本，希望楼主可以写一下各个模块的基本版本

**Comment by yinchangchang** [comment]
版本已经在readme和requirement.txt里写过了，你可以试下

**Comment by ww451575464** [comment]
非常感谢。。。之前试了下，由于使用python2，matplot装不上，这就导致好几个模块安装不上，再次感谢
