### ISSUE TITLE
请问如何运行一下demo查看效果？

### ISSUE THREAD

**Issue by DaisyLoveU** [yinchangchang/ocr_densenet#4]
请问如何直接使用训练好的模型，更换图片测试效果？  
还有头疼的模块版本问题，可以帮忙给出所用模块版本吗？  
<b>不胜感激~！

**Comment by yinchangchang** [comment]
如果更换数据，需要把图片和标签处理成相应的格式，这是Readme里的预处理部分。
用的python2.7，pytorch对应的版本即可

**Comment by DaisyLoveU** [comment]
@yinchangchang  尝试一下，感谢
